### ISSUE TITLE
Broken mysheetsite.com

### ISSUE THREAD

**Issue by boris-badenov** [jonathanjanssens/hugo-casper3-demo#5]
Hello! Sorry, don't know how to contact you :) 
I want to ask what's wrong with mysheetsite.com and will it be fixed / maintained ? Looks like a good idea!
@jonathanjanssens

**Comment by jonathanjanssens** [comment]
Hello, sorry for the issue you are having. Please email support@oostapps.com with some details and I will get back to you personally.

Thanks
